---
kind: FirewallRule
metadata:
  name: allow-ssh
  description: Allow ssh traffic to all production servers from a jump host
spec:
  hosts: prod
  template: "-A INPUT -d { host.privateIp } -s 192.168.99.99 -p tcp --dport 22 -j ACCEPT"